### ISSUE TITLE
Fatal error on running the test cases

### ISSUE THREAD

**Issue by asikrhmn** [vivaladav/BitsOfBytes#2]
When I am trying to run my test cases its throwing a fatal error "Test for project "xyz" did not produce any expected output". 
Any idea?

**Comment by crazafimahatratra** [comment]
Unable to run test :

error: cannot find -lWidgetsLib

**Comment by asikrhmn** [comment]
> Unable to run test :
> 
> error: cannot find -lWidgetsLib

I figured that the problem was in my project, it couldn't find a library module in the test module that I had used in the main project. Adding the library path to the LD_LIBRARY_PATH solved the error for me. I think you are also missing something similar.

**Comment by crazafimahatratra** [comment]
Hi @asikrhmn

Thanks. Ill give it a try.

**Comment by vivaladav** [comment]
This doesn't seem relevant to the code in this repo.
