### ISSUE TITLE
Qt QML variant available for your QtSqlExample

### ISSUE THREAD

**Issue by tanius** [vivaladav/BitsOfBytes#3]
I like your [QtSqlExample](https://github.com/vivaladav/BitsOfBytes/tree/master/howto-embed-database-in-application-with-sqlite-and-qt) in this repository.

But because my application uses QML and not QWidgets, I created a variant of this example using QML from which I can now continue to work. It duplicates the functionality of your example.

I thought you might be interested to mention this QML variant in [your blog post](http://blog.davidecoppola.com/2016/11/howto-embed-database-in-application-with-sqlite-and-qt/) or include it into this repo [here](https://github.com/vivaladav/BitsOfBytes/tree/master/howto-embed-database-in-application-with-sqlite-and-qt). Very welcome to do so; the code is under Unlicense just as your original repo.

**Comment by vivaladav** [comment]
Hi @tanius, I believe you're referring to this [repo](https://github.com/tanius/qml-sql-example).

I just opened an issue in your repo, when you fix it I will link it in the README of mine.

**Comment by tanius** [comment]
Glad you found the repo link I forgot to add. :smile: A link in the README would be great.

(And thank you for the testing and issue report, I just fixed it.)

**Comment by vivaladav** [comment]
No worries, all done.
